# Generated by Django 3.2.17 on 2023-03-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Late', 'Late'), ('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Holiday', 'Holiday')], max_length=10),
        ),
    ]
