# Generated by Django 3.2.17 on 2023-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_name_events_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='event',
        ),
        migrations.AddField(
            model_name='events',
            name='event_status',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
