# Generated by Django 3.2.17 on 2023-03-13 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20230311_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='deduction',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='overttimeBonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='salary',
        ),
        migrations.AddField(
            model_name='payroll',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payroll',
            name='deductions',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='net_pay',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
